CrtLibSupport: Fix rdstc() for the SVSM bindgen
The SVSM bindgen fails to generate the bindings due to the rdtsc()
function name.

Error:

libcrt/include/CrtLibSupport.h:258:34: error: definition of builtin function '__rdtsc'
thread 'main' panicked at 'ERROR: Unable to generate bindings:
    ClangDiagnostic("libcrt/include/CrtLibSupport.h:
    258:34: error: definition of builtin function '__rdtsc'\n")', build.rs:25:10

This patch renames the __rdtsc() to rdtsc(), without the two
underscores.

Signed-off-by: Claudio Carvalho <cclaudio@linux.ibm.com>